services:
  - type: web
    name: pivo
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/v1/healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: TEST_ACCESS_USER
        sync: false
      - key: TEST_ACCESS_PASSWORD
        sync: false
      - key: MARKET_BENCHMARK_CONNECTOR_URL
        sync: false
      - key: DATABASE_URL
        sync: false
