export interface LaborProfile {
  id: string;
  title: string;
  seniority: "Junior" | "Pleno" | "Senior" | "Especialista";
  cbo: string;
  employmentModel: "CLT" | "PJ";
  monthlyCompensation: number;
  factorK: number;
  benchmarkSource: string;
  sourceStatus: "FALLBACK_STALE";
  updatedAt: string;
}

export interface LicenseCatalogItem {
  id: string;
  vendor: string;
  product: string;
  plan: string;
  billingMetric: string;
  unitPriceUsd: number;
  minimumSeats: number;
  category: "DevOps" | "Produtividade" | "Observabilidade" | "Seguranca" | "Dados" | "Colaboracao" | "ITSM";
  billingCycle: "monthly" | "annual-paid-monthly";
  sourceUrl: string;
  source: string;
  sourceStatus: "FALLBACK_STALE";
  notes: string;
  updatedAt: string;
}

export const laborProfiles: LaborProfile[] = [
  {
    id: "dev-pleno-clt",
    title: "Desenvolvedor Full Stack",
    seniority: "Pleno",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 11800,
    factorK: 1.86,
    benchmarkSource: "CAGED/MTE - snapshot tecnologia",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "dev-senior-pj",
    title: "Desenvolvedor Backend",
    seniority: "Senior",
    cbo: "2124-05",
    employmentModel: "PJ",
    monthlyCompensation: 15500,
    factorK: 1.42,
    benchmarkSource: "CAGED/MTE - snapshot tecnologia",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "analista-pleno-clt",
    title: "Analista de Sistemas",
    seniority: "Pleno",
    cbo: "2124-20",
    employmentModel: "CLT",
    monthlyCompensation: 10400,
    factorK: 1.82,
    benchmarkSource: "CAGED/MTE - snapshot tecnologia",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "arquiteto-senior-pj",
    title: "Arquiteto de Solucoes",
    seniority: "Senior",
    cbo: "2124-10",
    employmentModel: "PJ",
    monthlyCompensation: 22000,
    factorK: 1.38,
    benchmarkSource: "CAGED/MTE - snapshot tecnologia",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "dados-especialista-pj",
    title: "Engenheiro de Dados",
    seniority: "Especialista",
    cbo: "2124-15",
    employmentModel: "PJ",
    monthlyCompensation: 20500,
    factorK: 1.4,
    benchmarkSource: "CAGED/MTE - snapshot tecnologia",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-08-01T00:00:00.000Z",
  },
];

export const licenseCatalog: LicenseCatalogItem[] = [
  {
    id: "github-team",
    vendor: "GitHub",
    product: "GitHub",
    plan: "Team",
    billingMetric: "usuario/mes",
    unitPriceUsd: 4,
    minimumSeats: 1,
    category: "DevOps",
    billingCycle: "monthly",
    sourceUrl: "https://github.com/pricing",
    source: "GitHub Pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Plano de colaboracao para times; consumo de Actions/Codespaces pode gerar adicional.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "github-enterprise",
    vendor: "GitHub",
    product: "GitHub",
    plan: "Enterprise Cloud",
    billingMetric: "usuario/mes",
    unitPriceUsd: 21,
    minimumSeats: 1,
    category: "DevOps",
    billingCycle: "monthly",
    sourceUrl: "https://github.com/pricing",
    source: "GitHub Pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Licenca por usuario unico; extras como Copilot e Advanced Security sao cobrados separadamente.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "github-copilot-business",
    vendor: "GitHub",
    product: "GitHub Copilot",
    plan: "Business",
    billingMetric: "usuario/mes",
    unitPriceUsd: 19,
    minimumSeats: 1,
    category: "DevOps",
    billingCycle: "monthly",
    sourceUrl: "https://docs.github.com/en/copilot/concepts/billing/organizations-and-enterprises",
    source: "GitHub Docs - Copilot billing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Inclui creditos de IA por usuario; excedentes podem variar conforme politica vigente.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "m365-business-premium",
    vendor: "Microsoft",
    product: "Microsoft 365",
    plan: "Business Premium",
    billingMetric: "usuario/mes",
    unitPriceUsd: 22,
    minimumSeats: 1,
    category: "Produtividade",
    billingCycle: "annual-paid-monthly",
    sourceUrl: "https://www.microsoft.com/en-us/microsoft-365/business/microsoft-365-business-premium",
    source: "Microsoft 365 pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Preco anual com pagamento mensal; impostos e moeda local variam por tenant/contrato.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "m365-business-premium-no-teams",
    vendor: "Microsoft",
    product: "Microsoft 365",
    plan: "Business Premium sem Teams",
    billingMetric: "usuario/mes",
    unitPriceUsd: 18.79,
    minimumSeats: 1,
    category: "Produtividade",
    billingCycle: "annual-paid-monthly",
    sourceUrl: "https://www.microsoft.com/en-us/microsoft-365/business/microsoft-365-business-premium",
    source: "Microsoft 365 pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Variante sem Teams, util para cenarios com licenciamento separado de colaboracao.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "datadog-infra-pro",
    vendor: "Datadog",
    product: "Infrastructure Monitoring",
    plan: "Pro",
    billingMetric: "host/mes",
    unitPriceUsd: 15,
    minimumSeats: 1,
    category: "Observabilidade",
    billingCycle: "annual-paid-monthly",
    sourceUrl: "https://www.datadoghq.com/pricing/list/",
    source: "Datadog Pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Datadog mede hosts por high-water mark ou modelo hibrido mensal/horario conforme contrato.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "datadog-apm-standalone",
    vendor: "Datadog",
    product: "APM",
    plan: "Standalone",
    billingMetric: "host/mes",
    unitPriceUsd: 36,
    minimumSeats: 1,
    category: "Observabilidade",
    billingCycle: "annual-paid-monthly",
    sourceUrl: "https://www.datadoghq.com/pricing/",
    source: "Datadog Pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "APM standalone nao exige Infrastructure Monitoring no mesmo host.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "power-bi-pro",
    vendor: "Microsoft",
    product: "Power BI",
    plan: "Pro",
    billingMetric: "usuario/mes",
    unitPriceUsd: 14,
    minimumSeats: 1,
    category: "Dados",
    billingCycle: "annual-paid-monthly",
    sourceUrl: "https://www.microsoft.com/en-us/power-platform/products/power-bi/pricing",
    source: "Microsoft Power BI pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Licenca para publicar, compartilhar e consumir relatorios Power BI.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "power-bi-premium-user",
    vendor: "Microsoft",
    product: "Power BI",
    plan: "Premium Per User",
    billingMetric: "usuario/mes",
    unitPriceUsd: 24,
    minimumSeats: 1,
    category: "Dados",
    billingCycle: "annual-paid-monthly",
    sourceUrl: "https://www.microsoft.com/en-us/power-platform/products/power-bi/pricing",
    source: "Microsoft Power BI pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Recursos avancados por usuario; capacidade Fabric/Embedded e precificacao variavel ficam fora desta linha.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "jira-standard",
    vendor: "Atlassian",
    product: "Jira",
    plan: "Standard",
    billingMetric: "usuario/mes",
    unitPriceUsd: 7.91,
    minimumSeats: 1,
    category: "ITSM",
    billingCycle: "monthly",
    sourceUrl: "https://www.atlassian.com/software/jira/jira/pricing",
    source: "Atlassian Jira pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Atlassian usa cobranca por usuario e pode aplicar faixas progressivas/MQB.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "jira-premium",
    vendor: "Atlassian",
    product: "Jira",
    plan: "Premium",
    billingMetric: "usuario/mes",
    unitPriceUsd: 14.54,
    minimumSeats: 1,
    category: "ITSM",
    billingCycle: "monthly",
    sourceUrl: "https://www.atlassian.com/software/jira/jira/pricing",
    source: "Atlassian Jira pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Inclui recursos avancados; enterprise exige contato comercial.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "slack-pro",
    vendor: "Slack",
    product: "Slack",
    plan: "Pro",
    billingMetric: "usuario/mes",
    unitPriceUsd: 8.75,
    minimumSeats: 1,
    category: "Colaboracao",
    billingCycle: "monthly",
    sourceUrl: "https://slack.com/pricing",
    source: "Slack Pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Preco mensal; plano anual costuma ter valor menor por usuario ativo.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "slack-business-plus",
    vendor: "Slack",
    product: "Slack",
    plan: "Business+",
    billingMetric: "usuario/mes",
    unitPriceUsd: 18,
    minimumSeats: 1,
    category: "Colaboracao",
    billingCycle: "monthly",
    sourceUrl: "https://slack.com/pricing",
    source: "Slack Pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Inclui recursos administrativos/SSO; comparar com preco anual em contratos maiores.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
];

export function getLaborProfile(profileId: string): LaborProfile | undefined {
  return laborProfiles.find((profile) => profile.id === profileId);
}
