export interface LaborProfile {
  id: string;
  title: string;
  seniority: "Junior" | "Pleno" | "Senior" | "Especialista";
  cbo: string;
  employmentModel: "CLT" | "PJ";
  monthlyCompensation: number;
  factorK: number;
  benchmarkSource: string;
  sourceStatus: "FALLBACK_STALE";
  updatedAt: string;
}

export interface LicenseCatalogItem {
  id: string;
  vendor: string;
  product: string;
  plan: string;
  billingMetric: string;
  unitPriceUsd: number;
  minimumSeats: number;
  category: "DevOps" | "Produtividade" | "Observabilidade" | "Seguranca" | "Dados" | "Colaboracao" | "ITSM";
  billingCycle: "monthly" | "annual-paid-monthly";
  sourceUrl: string;
  source: string;
  sourceStatus: "FALLBACK_STALE";
  notes: string;
  updatedAt: string;
}

export const laborProfiles: LaborProfile[] = [
  {
    id: "dev-pleno-clt",
    title: "Desenvolvedor Full Stack",
    seniority: "Pleno",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 11800,
    factorK: 1.86,
    benchmarkSource: "CAGED/MTE - snapshot tecnologia",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "dev-senior-pj",
    title: "Desenvolvedor Backend",
    seniority: "Senior",
    cbo: "2124-05",
    employmentModel: "PJ",
    monthlyCompensation: 15500,
    factorK: 1.42,
    benchmarkSource: "CAGED/MTE - snapshot tecnologia",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "analista-pleno-clt",
    title: "Analista de Sistemas",
    seniority: "Pleno",
    cbo: "2124-20",
    employmentModel: "CLT",
    monthlyCompensation: 10400,
    factorK: 1.82,
    benchmarkSource: "CAGED/MTE - snapshot tecnologia",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "arquiteto-senior-pj",
    title: "Arquiteto de Solucoes",
    seniority: "Senior",
    cbo: "2124-10",
    employmentModel: "PJ",
    monthlyCompensation: 22000,
    factorK: 1.38,
    benchmarkSource: "CAGED/MTE - snapshot tecnologia",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "dados-especialista-pj",
    title: "Engenheiro de Dados",
    seniority: "Especialista",
    cbo: "2124-15",
    employmentModel: "PJ",
    monthlyCompensation: 20500,
    factorK: 1.4,
    benchmarkSource: "CAGED/MTE - snapshot tecnologia",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "sgd-tecsup-01",
    title: "Tecnico de suporte ao usuario de tecnologia da informacao",
    seniority: "Junior",
    cbo: "3171-05",
    employmentModel: "CLT",
    monthlyCompensation: 1800,
    factorK: 2.65,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-tecsup-02",
    title: "Tecnico de suporte ao usuario de tecnologia da informacao",
    seniority: "Pleno",
    cbo: "3171-05",
    employmentModel: "CLT",
    monthlyCompensation: 2326.82,
    factorK: 2.46,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-tecsup-03",
    title: "Tecnico de suporte ao usuario de tecnologia da informacao",
    seniority: "Senior",
    cbo: "3171-05",
    employmentModel: "CLT",
    monthlyCompensation: 3216.87,
    factorK: 2.28,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-tecman-01",
    title: "Tecnico em manutencao de equipamentos de informatica",
    seniority: "Junior",
    cbo: "3171-05",
    employmentModel: "CLT",
    monthlyCompensation: 1950,
    factorK: 2.58,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-tecman-02",
    title: "Tecnico em manutencao de equipamentos de informatica",
    seniority: "Pleno",
    cbo: "3171-05",
    employmentModel: "CLT",
    monthlyCompensation: 2505.12,
    factorK: 2.42,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-tecman-03",
    title: "Tecnico em manutencao de equipamentos de informatica",
    seniority: "Senior",
    cbo: "3171-05",
    employmentModel: "CLT",
    monthlyCompensation: 3273.71,
    factorK: 2.27,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-gersup",
    title: "Gerente de suporte tecnico de tecnologia da informacao",
    seniority: "Especialista",
    cbo: "1425-10",
    employmentModel: "CLT",
    monthlyCompensation: 10365.31,
    factorK: 1.98,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-asupcomp-01",
    title: "Analista de suporte computacional",
    seniority: "Junior",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 3781.48,
    factorK: 2.21,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-asupcomp-02",
    title: "Analista de suporte computacional",
    seniority: "Pleno",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 5075.52,
    factorK: 2.12,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-asupcomp-03",
    title: "Analista de suporte computacional",
    seniority: "Senior",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 7487.05,
    factorK: 2.03,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-gerinf",
    title: "Gerente de infraestrutura de tecnologia da informacao",
    seniority: "Especialista",
    cbo: "1425-10",
    employmentModel: "CLT",
    monthlyCompensation: 17851.64,
    factorK: 1.94,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-abd-01",
    title: "Administrador de banco de dados",
    seniority: "Junior",
    cbo: "2124-15",
    employmentModel: "CLT",
    monthlyCompensation: 4625.1,
    factorK: 2.14,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-abd-02",
    title: "Administrador de banco de dados",
    seniority: "Pleno",
    cbo: "2124-15",
    employmentModel: "CLT",
    monthlyCompensation: 6700.63,
    factorK: 2.05,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-abd-03",
    title: "Administrador de banco de dados",
    seniority: "Senior",
    cbo: "2124-15",
    employmentModel: "CLT",
    monthlyCompensation: 10800.36,
    factorK: 1.98,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-aso-01",
    title: "Administrador de sistemas operacionais",
    seniority: "Junior",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 4750,
    factorK: 2.13,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-aso-02",
    title: "Administrador de sistemas operacionais",
    seniority: "Pleno",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 6404.69,
    factorK: 2.06,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-aso-03",
    title: "Administrador de sistemas operacionais",
    seniority: "Senior",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 9542.92,
    factorK: 1.99,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-ared-01",
    title: "Analista de redes e de comunicacao de dados",
    seniority: "Junior",
    cbo: "2124-10",
    employmentModel: "CLT",
    monthlyCompensation: 4433.33,
    factorK: 2.15,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-ared-02",
    title: "Analista de redes e de comunicacao de dados",
    seniority: "Pleno",
    cbo: "2124-10",
    employmentModel: "CLT",
    monthlyCompensation: 7384.26,
    factorK: 2.04,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-ared-03",
    title: "Analista de redes e de comunicacao de dados",
    seniority: "Senior",
    cbo: "2124-10",
    employmentModel: "CLT",
    monthlyCompensation: 10333.33,
    factorK: 1.98,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-tecred-01",
    title: "Tecnico de rede (telecomunicacoes)",
    seniority: "Junior",
    cbo: "3171-05",
    employmentModel: "CLT",
    monthlyCompensation: 1828.9,
    factorK: 2.64,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-tecred-02",
    title: "Tecnico de rede (telecomunicacoes)",
    seniority: "Pleno",
    cbo: "3171-05",
    employmentModel: "CLT",
    monthlyCompensation: 2517.46,
    factorK: 2.41,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-tecred-03",
    title: "Tecnico de rede (telecomunicacoes)",
    seniority: "Senior",
    cbo: "3171-05",
    employmentModel: "CLT",
    monthlyCompensation: 3929.79,
    factorK: 2.19,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-destec-01",
    title: "Desenvolvedor de sistemas de tecnologia da informacao",
    seniority: "Junior",
    cbo: "2124-30",
    employmentModel: "CLT",
    monthlyCompensation: 5343.12,
    factorK: 2.1,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-destec-02",
    title: "Desenvolvedor de sistemas de tecnologia da informacao",
    seniority: "Pleno",
    cbo: "2124-30",
    employmentModel: "CLT",
    monthlyCompensation: 11000,
    factorK: 1.98,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-destec-03",
    title: "Desenvolvedor de sistemas de tecnologia da informacao",
    seniority: "Senior",
    cbo: "2124-30",
    employmentModel: "CLT",
    monthlyCompensation: 15025.93,
    factorK: 1.95,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-asisa-01",
    title: "Analista de sistemas de automacao",
    seniority: "Junior",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 5536.11,
    factorK: 2.1,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-asisa-02",
    title: "Analista de sistemas de automacao",
    seniority: "Pleno",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 8755.2,
    factorK: 2.01,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-asisa-03",
    title: "Analista de sistemas de automacao",
    seniority: "Senior",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 11283,
    factorK: 1.98,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-aseg-01",
    title: "Administrador em seguranca da informacao",
    seniority: "Junior",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 6966.67,
    factorK: 2.05,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-aseg-02",
    title: "Administrador em seguranca da informacao",
    seniority: "Pleno",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 9716.67,
    factorK: 1.99,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-aseg-03",
    title: "Administrador em seguranca da informacao",
    seniority: "Senior",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 15056.97,
    factorK: 1.95,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-gerseg",
    title: "Gerente de seguranca da informacao",
    seniority: "Especialista",
    cbo: "1425-10",
    employmentModel: "CLT",
    monthlyCompensation: 21333.33,
    factorK: 1.93,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-cloud-01",
    title: "Especialista em Cloud",
    seniority: "Pleno",
    cbo: "2124-10",
    employmentModel: "CLT",
    monthlyCompensation: 11774.28,
    factorK: 1.97,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-cloud-02",
    title: "Especialista em Cloud",
    seniority: "Senior",
    cbo: "2124-10",
    employmentModel: "CLT",
    monthlyCompensation: 16985.65,
    factorK: 1.94,
    benchmarkSource: "Portaria SGD/MGI no 6.055/2025 (Anexo II da Portaria SGD/MGI no 1.070/2023) - Mapa de Pesquisa Salarial SISP, servicos de operacao de infraestrutura e atendimento a usuarios de TIC",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2025-08-28T00:00:00.000Z",
  },
  {
    id: "sgd-arqsof-01",
    title: "Arquiteto de Software",
    seniority: "Pleno",
    cbo: "2124-25",
    employmentModel: "CLT",
    monthlyCompensation: 15580.79,
    factorK: 1.99,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-arqsof-02",
    title: "Arquiteto de Software",
    seniority: "Senior",
    cbo: "2124-25",
    employmentModel: "CLT",
    monthlyCompensation: 19078.14,
    factorK: 1.98,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-atq-01",
    title: "Analista de Testes/Qualidade",
    seniority: "Junior",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 5568.74,
    factorK: 2.15,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-atq-02",
    title: "Analista de Testes/Qualidade",
    seniority: "Pleno",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 8616.67,
    factorK: 2.06,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-atq-03",
    title: "Analista de Testes/Qualidade",
    seniority: "Senior",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 13883.33,
    factorK: 2,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-desenv-01",
    title: "Desenvolvedor de Software",
    seniority: "Junior",
    cbo: "2124-30",
    employmentModel: "CLT",
    monthlyCompensation: 6687.85,
    factorK: 2.11,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-desenv-02",
    title: "Desenvolvedor de Software",
    seniority: "Pleno",
    cbo: "2124-30",
    employmentModel: "CLT",
    monthlyCompensation: 11023.35,
    factorK: 2.03,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-desenv-03",
    title: "Desenvolvedor de Software",
    seniority: "Senior",
    cbo: "2124-30",
    employmentModel: "CLT",
    monthlyCompensation: 16205.18,
    factorK: 1.99,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-anr-01",
    title: "Analista de Negocios/Requisitos",
    seniority: "Junior",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 6757.02,
    factorK: 2.1,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-anr-02",
    title: "Analista de Negocios/Requisitos",
    seniority: "Pleno",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 9561.11,
    factorK: 2.04,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-anr-03",
    title: "Analista de Negocios/Requisitos",
    seniority: "Senior",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 12193.99,
    factorK: 2.02,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-abi-01",
    title: "Analista de BI",
    seniority: "Junior",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 7588.47,
    factorK: 2.08,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-abi-02",
    title: "Analista de BI",
    seniority: "Pleno",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 11071.12,
    factorK: 2.02,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-abi-03",
    title: "Analista de BI",
    seniority: "Senior",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 14490.34,
    factorK: 2,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-adados-02",
    title: "Administrador de Dados",
    seniority: "Pleno",
    cbo: "2124-15",
    employmentModel: "CLT",
    monthlyCompensation: 7936.98,
    factorK: 2.07,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-adados-03",
    title: "Administrador de Dados",
    seniority: "Senior",
    cbo: "2124-15",
    employmentModel: "CLT",
    monthlyCompensation: 11673.56,
    factorK: 2.02,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-ldesenv",
    title: "Lider Tecnico de Desenvolvimento",
    seniority: "Especialista",
    cbo: "2124-30",
    employmentModel: "CLT",
    monthlyCompensation: 19065.28,
    factorK: 1.98,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-scrum",
    title: "Scrum Master",
    seniority: "Especialista",
    cbo: "1425-15",
    employmentModel: "CLT",
    monthlyCompensation: 12312.5,
    factorK: 2.01,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-gerpro",
    title: "Gerente de projetos de tecnologia da informacao",
    seniority: "Especialista",
    cbo: "1425-10",
    employmentModel: "CLT",
    monthlyCompensation: 17138.03,
    factorK: 1.99,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-auxui-01",
    title: "Analista de UX/UI",
    seniority: "Pleno",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 7877.75,
    factorK: 2.07,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-auxui-02",
    title: "Analista de UX/UI",
    seniority: "Senior",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 12878.4,
    factorK: 2.01,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-cdados-01",
    title: "Cientista de Dados",
    seniority: "Junior",
    cbo: "2124-15",
    employmentModel: "CLT",
    monthlyCompensation: 8466.82,
    factorK: 2.06,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-cdados-02",
    title: "Cientista de Dados",
    seniority: "Pleno",
    cbo: "2124-15",
    employmentModel: "CLT",
    monthlyCompensation: 13554.04,
    factorK: 2.01,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-cdados-03",
    title: "Cientista de Dados",
    seniority: "Senior",
    cbo: "2124-15",
    employmentModel: "CLT",
    monthlyCompensation: 19549.1,
    factorK: 1.98,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-arqdados-01",
    title: "Arquiteto de Dados",
    seniority: "Junior",
    cbo: "2124-15",
    employmentModel: "CLT",
    monthlyCompensation: 9299.2,
    factorK: 2.04,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-arqdados-02",
    title: "Arquiteto de Dados",
    seniority: "Pleno",
    cbo: "2124-15",
    employmentModel: "CLT",
    monthlyCompensation: 13982.75,
    factorK: 2,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-arqdados-03",
    title: "Arquiteto de Dados",
    seniority: "Senior",
    cbo: "2124-15",
    employmentModel: "CLT",
    monthlyCompensation: 18520.2,
    factorK: 1.98,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-ia-eng-01",
    title: "Engenheiro de IA",
    seniority: "Junior",
    cbo: "2124-15",
    employmentModel: "CLT",
    monthlyCompensation: 8745.65,
    factorK: 2.06,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-ia-eng-02",
    title: "Engenheiro de IA",
    seniority: "Pleno",
    cbo: "2124-15",
    employmentModel: "CLT",
    monthlyCompensation: 14370.3,
    factorK: 2,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-ia-eng-03",
    title: "Engenheiro de IA",
    seniority: "Senior",
    cbo: "2124-15",
    employmentModel: "CLT",
    monthlyCompensation: 16976.85,
    factorK: 1.99,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-metrica-01",
    title: "Analista de Metricas",
    seniority: "Junior",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 5568.74,
    factorK: 2.15,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-metrica-02",
    title: "Analista de Metricas",
    seniority: "Pleno",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 8616.67,
    factorK: 2.06,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
  {
    id: "sgd-metrica-03",
    title: "Analista de Metricas",
    seniority: "Senior",
    cbo: "2124-05",
    employmentModel: "CLT",
    monthlyCompensation: 13883.33,
    factorK: 2,
    benchmarkSource: "Portaria SGD/MGI no 4.777/2026 (Anexo II da Portaria SGD/MGI no 750/2023) - Mapa de Pesquisa Salarial SISP, servicos de desenvolvimento e sustentacao de software",
    sourceStatus: "FALLBACK_STALE",
    updatedAt: "2026-06-17T00:00:00.000Z",
  },
];

export const licenseCatalog: LicenseCatalogItem[] = [
  {
    id: "github-team",
    vendor: "GitHub",
    product: "GitHub",
    plan: "Team",
    billingMetric: "usuario/mes",
    unitPriceUsd: 4,
    minimumSeats: 1,
    category: "DevOps",
    billingCycle: "monthly",
    sourceUrl: "https://github.com/pricing",
    source: "GitHub Pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Plano de colaboracao para times; consumo de Actions/Codespaces pode gerar adicional.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "github-enterprise",
    vendor: "GitHub",
    product: "GitHub",
    plan: "Enterprise Cloud",
    billingMetric: "usuario/mes",
    unitPriceUsd: 21,
    minimumSeats: 1,
    category: "DevOps",
    billingCycle: "monthly",
    sourceUrl: "https://github.com/pricing",
    source: "GitHub Pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Licenca por usuario unico; extras como Copilot e Advanced Security sao cobrados separadamente.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "github-copilot-business",
    vendor: "GitHub",
    product: "GitHub Copilot",
    plan: "Business",
    billingMetric: "usuario/mes",
    unitPriceUsd: 19,
    minimumSeats: 1,
    category: "DevOps",
    billingCycle: "monthly",
    sourceUrl: "https://docs.github.com/en/copilot/concepts/billing/organizations-and-enterprises",
    source: "GitHub Docs - Copilot billing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Inclui creditos de IA por usuario; excedentes podem variar conforme politica vigente.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "m365-business-premium",
    vendor: "Microsoft",
    product: "Microsoft 365",
    plan: "Business Premium",
    billingMetric: "usuario/mes",
    unitPriceUsd: 22,
    minimumSeats: 1,
    category: "Produtividade",
    billingCycle: "annual-paid-monthly",
    sourceUrl: "https://www.microsoft.com/en-us/microsoft-365/business/microsoft-365-business-premium",
    source: "Microsoft 365 pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Preco anual com pagamento mensal; impostos e moeda local variam por tenant/contrato.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "m365-business-premium-no-teams",
    vendor: "Microsoft",
    product: "Microsoft 365",
    plan: "Business Premium sem Teams",
    billingMetric: "usuario/mes",
    unitPriceUsd: 18.79,
    minimumSeats: 1,
    category: "Produtividade",
    billingCycle: "annual-paid-monthly",
    sourceUrl: "https://www.microsoft.com/en-us/microsoft-365/business/microsoft-365-business-premium",
    source: "Microsoft 365 pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Variante sem Teams, util para cenarios com licenciamento separado de colaboracao.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "datadog-infra-pro",
    vendor: "Datadog",
    product: "Infrastructure Monitoring",
    plan: "Pro",
    billingMetric: "host/mes",
    unitPriceUsd: 15,
    minimumSeats: 1,
    category: "Observabilidade",
    billingCycle: "annual-paid-monthly",
    sourceUrl: "https://www.datadoghq.com/pricing/list/",
    source: "Datadog Pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Datadog mede hosts por high-water mark ou modelo hibrido mensal/horario conforme contrato.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "datadog-apm-standalone",
    vendor: "Datadog",
    product: "APM",
    plan: "Standalone",
    billingMetric: "host/mes",
    unitPriceUsd: 36,
    minimumSeats: 1,
    category: "Observabilidade",
    billingCycle: "annual-paid-monthly",
    sourceUrl: "https://www.datadoghq.com/pricing/",
    source: "Datadog Pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "APM standalone nao exige Infrastructure Monitoring no mesmo host.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "power-bi-pro",
    vendor: "Microsoft",
    product: "Power BI",
    plan: "Pro",
    billingMetric: "usuario/mes",
    unitPriceUsd: 14,
    minimumSeats: 1,
    category: "Dados",
    billingCycle: "annual-paid-monthly",
    sourceUrl: "https://www.microsoft.com/en-us/power-platform/products/power-bi/pricing",
    source: "Microsoft Power BI pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Licenca para publicar, compartilhar e consumir relatorios Power BI.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "power-bi-premium-user",
    vendor: "Microsoft",
    product: "Power BI",
    plan: "Premium Per User",
    billingMetric: "usuario/mes",
    unitPriceUsd: 24,
    minimumSeats: 1,
    category: "Dados",
    billingCycle: "annual-paid-monthly",
    sourceUrl: "https://www.microsoft.com/en-us/power-platform/products/power-bi/pricing",
    source: "Microsoft Power BI pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Recursos avancados por usuario; capacidade Fabric/Embedded e precificacao variavel ficam fora desta linha.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "jira-standard",
    vendor: "Atlassian",
    product: "Jira",
    plan: "Standard",
    billingMetric: "usuario/mes",
    unitPriceUsd: 7.91,
    minimumSeats: 1,
    category: "ITSM",
    billingCycle: "monthly",
    sourceUrl: "https://www.atlassian.com/software/jira/jira/pricing",
    source: "Atlassian Jira pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Atlassian usa cobranca por usuario e pode aplicar faixas progressivas/MQB.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "jira-premium",
    vendor: "Atlassian",
    product: "Jira",
    plan: "Premium",
    billingMetric: "usuario/mes",
    unitPriceUsd: 14.54,
    minimumSeats: 1,
    category: "ITSM",
    billingCycle: "monthly",
    sourceUrl: "https://www.atlassian.com/software/jira/jira/pricing",
    source: "Atlassian Jira pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Inclui recursos avancados; enterprise exige contato comercial.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "slack-pro",
    vendor: "Slack",
    product: "Slack",
    plan: "Pro",
    billingMetric: "usuario/mes",
    unitPriceUsd: 8.75,
    minimumSeats: 1,
    category: "Colaboracao",
    billingCycle: "monthly",
    sourceUrl: "https://slack.com/pricing",
    source: "Slack Pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Preco mensal; plano anual costuma ter valor menor por usuario ativo.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "slack-business-plus",
    vendor: "Slack",
    product: "Slack",
    plan: "Business+",
    billingMetric: "usuario/mes",
    unitPriceUsd: 18,
    minimumSeats: 1,
    category: "Colaboracao",
    billingCycle: "monthly",
    sourceUrl: "https://slack.com/pricing",
    source: "Slack Pricing",
    sourceStatus: "FALLBACK_STALE",
    notes: "Inclui recursos administrativos/SSO; comparar com preco anual em contratos maiores.",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
];

export function getLaborProfile(profileId: string): LaborProfile | undefined {
  return laborProfiles.find((profile) => profile.id === profileId);
}
